services:
  student-db:
    image: postgres:15
    container_name: student-db
    environment:
      POSTGRES_USER: student
      POSTGRES_PASSWORD: password
      POSTGRES_DB: students
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - microservices-net

  student-profile:
    build: ./student-profile
    container_name: student-profile
    environment:
      DATABASE_URL: postgresql://student:password@student-db:5432/students
      FLASK_ENV: development
    depends_on:
      - student-db
    ports:
      - "5001:5001"
    networks:
      - microservices-net

  course-db:
    image: postgres:15
    container_name: course-db
    environment:
      POSTGRES_USER: course
      POSTGRES_PASSWORD: password
      POSTGRES_DB: courses
    ports:
      - "6432:6432"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - microservices-net

  course-feedback:
    build: ./course-feedback
    container_name: course-feedback
    environment:
      DATABASE_URL: postgresql://course:password@course-db:6432/courses
    depends_on:
      - course-db
    ports:
      - "6001:6001"
    networks:
      - microservices-net


  feedback:
    build: ./feedback
    container_name: feedback
    ports:
      - "3001:3001"
    volumes:
      - ./feedback:/app
      - /app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"
    depends_on:
      - course-feedback
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge
